.TH jpegqs 1 "08 Apr 2021" "JPEG Quant Smooth"
.SH NAME
.B JPEG Quant Smooth
\- JPEG artifacts removal
.SH DESCRIPTION
This program tries to recover the lost precision of DCT coefficients
based on a quantization table from a JPEG image. The result is saved
as a JPEG image with quantization set to 1 (like a JPEG saved at 100%
quality).
.SH SYNOPSIS
.B jpegqs
.IR "" [ options ]
.I input.jpg
.I output.jpg
.SH OPTIONS
.TP
.B \-q, \-\-quality n
Quality setting (0\-6, default is 3)/home/rainbow/Desktop/pngtest/jpegrestore/jpegqs.1
.TP
.B \-n, \-\-niter n
Number of iterations (default is 3)
.IP
* More iterations can make the result look like CG art, can make the photos look unnatural.
.TP
.B \-t, \-\-threads n
Set the number of CPU threads to use
.TP
.B \-o, \-\-optimize
Option for libjpeg to produce smaller output file
.TP
.B \-v, \-\-verbose n
Print libjpeg debug output
.TP
.B \-i, \-\-info n
Print quantsmooth debug output (default is 15).
.RS
Use the sum of flags:
.RS
0 \- silent
.RE
.RS
1/2/4 \- various information
.RE
.RS
8 \- processing time
.RE
.RS
16 \- SIMD type
.RE
.PP
* The processing time includes only the smoothing algorithm, jpeg reading and writing time is not included.
.RE
.TP
.B \-p, \-\-cpu n
Use to lower the SIMD type if CPU detection fails:
.RS
.RS
0 \- auto
.RE
.RS
1 \- scalar
.RE
.RS
2 \- SSE2
.RE
.RS
3 \- AVX2
.RE
.RS
4 \- AVX512
.RE
.PP
* x86 build selects between modes 1\-3, x86_64 from 2\-4
.RE
.SH QUALITY
.TP
The quality setting sets a combination of flags for processing:
.TP
3. default
.TP
4. adds DIAGONALS flag
smoother diagonal edges, ~1.5 times slower
.TP
5. adds JOINT_YUV flag
chroma channels will depend from luminance, better color consistency
.TP
6. adds UPSAMPLE_UV flag
non-blurring chroma upsampling, unlike fancy upsampling from libjpeg
.TP
levels 0\-2 is the same as 4\-6, but with LOW_QUALITY flag
.RS
.RE
~10 times faster, but the quality is lower
.RS
.RE
LOW_QUALITY implies DIAGONALS (always set)
.SH PROJECT PAGE
.TP
https://github.com/ilyakurdyukov/jpeg\-quantsmooth
.SH COPYRIGHT
.TP
Copyright (C) 2016\-2021 Ilya Kurdyukov
