
var b;b||(b=typeof Module !== 'undefined' ? Module : {});var r={},v;for(v in b)b.hasOwnProperty(v)&&(r[v]=b[v]);function x(a,c){throw c;}var y=!1,z=!1,aa=!1,ba=!1;y="object"===typeof window;z="function"===typeof importScripts;aa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ba=!y&&!aa&&!z;var A="",ca,B,da,ea;
if(aa)A=z?require("path").dirname(A)+"/":__dirname+"/",ca=function(a,c){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);return da.readFileSync(a,c?null:"utf8")},B=function(a){a=ca(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=b),process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;}),process.on("unhandledRejection",C),
x=function(a){process.exit(a)},b.inspect=function(){return"[Emscripten Module object]"};else if(ba)"undefined"!=typeof read&&(ca=function(a){return read(a)}),B=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(x=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:
print);else if(y||z)z?A=self.location.href:document.currentScript&&(A=document.currentScript.src),A=0!==A.indexOf("blob:")?A.substr(0,A.lastIndexOf("/")+1):"",ca=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},z&&(B=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var ha=b.print||console.log.bind(console),D=b.printErr||console.warn.bind(console);
for(v in r)r.hasOwnProperty(v)&&(b[v]=r[v]);r=null;b.quit&&(x=b.quit);function ia(a){ja||(ja={});ja[a]||(ja[a]=1,D(a))}var ja,E;b.wasmBinary&&(E=b.wasmBinary);var noExitRuntime;b.noExitRuntime&&(noExitRuntime=b.noExitRuntime);"object"!==typeof WebAssembly&&D("no native wasm support detected");var F,ka=new WebAssembly.Table({initial:81,maximum:81,element:"anyfunc"}),G=!1;function assert(a,c){a||C("Assertion failed: "+c)}
var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,H,I,J,ma,na;function oa(a){H=a;b.HEAP8=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=J=new Int32Array(a);b.HEAPU8=I=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=ma=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=na=new Float64Array(a)}var pa=b.INITIAL_MEMORY||16777216;b.wasmMemory?F=b.wasmMemory:F=new WebAssembly.Memory({initial:pa/65536,maximum:32768});F&&(H=F.buffer);pa=H.byteLength;oa(H);
J[3024]=5255136;function qa(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var e=c.w;"number"===typeof e?void 0===c.u?b.dynCall_v(e):b.dynCall_vi(e,c.u):e(void 0===c.u?null:c.u)}}}var ra=[],sa=[],ta=[],ua=[];function va(){var a=b.preRun.shift();ra.unshift(a)}var wa=Math.ceil,ya=Math.floor,K=0,za=null,L=null;b.preloadedImages={};b.preloadedAudios={};
function C(a){if(b.onAbort)b.onAbort(a);ha(a);D(a);G=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Aa(a){var c=M;return String.prototype.startsWith?c.startsWith(a):0===c.indexOf(a)}function Ba(){return Aa("data:application/octet-stream;base64,")}var M="quantsmooth.wasm";if(!Ba()){var Ca=M;M=b.locateFile?b.locateFile(Ca,A):A+Ca}
function Da(){try{if(E)return new Uint8Array(E);if(B)return B(M);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}function Ea(){return E||!y&&!z||"function"!==typeof fetch||Aa("file://")?new Promise(function(a){a(Da())}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Da()})}var Fa={1103:function(){setTimeout(b.wasm_return,0)}};sa.push({w:function(){Ga()}});
var Ha=[null,[],[]],Ia=[];
function Ja(a,c){Ka=a;La=c;if(N)if(0==a)O=function(){var d=Math.max(0,Ma+c-P())|0;setTimeout(Q,d)};else if(1==a)O=function(){Na(Q)};else if(2==a){if("undefined"===typeof setImmediate){var e=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),e.shift()()},!0);setImmediate=function(d){e.push(d);z?(void 0===b.setImmediates&&(b.setImmediates=[]),b.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}O=function(){setImmediate(Q)}}}var P;aa?P=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?P=dateNow:P=function(){return performance.now()};
function Oa(a){var c=Pa;noExitRuntime=!0;assert(!N,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");N=a;Pa=c;var e="undefined"!==typeof c?function(){b.dynCall_vi(a,c)}:function(){b.dynCall_v(a)};var d=R;Q=function(){if(!G)if(0<Qa.length){var f=Date.now(),g=Qa.shift();g.w(g.u);if(Ra){var h=Ra,m=0==h%1?h-1:Math.floor(h);Ra=g.G?m:(8*h+(m+.5))/9}console.log('main loop blocker "'+
g.name+'" took '+(Date.now()-f)+" ms");b.setStatus&&(f=b.statusMessage||"Please wait...",g=Ra,h=Sa.H,g?g<h?b.setStatus(f+" ("+(h-g)+"/"+h+")"):b.setStatus(f):b.setStatus(""));d<R||setTimeout(Q,0)}else if(!(d<R))if(Ta=Ta+1|0,1==Ka&&1<La&&0!=Ta%La)O();else{0==Ka&&(Ma=P());a:if(!(G||b.preMainLoop&&!1===b.preMainLoop())){try{e()}catch(k){if(k instanceof fa)break a;k&&"object"===typeof k&&k.stack&&D("exception thrown: "+[k,k.stack]);throw k;}b.postMainLoop&&b.postMainLoop()}d<R||("object"===typeof SDL&&
SDL.audio&&SDL.audio.C&&SDL.audio.C(),O())}}}var O=null,R=0,N=null,Pa=0,Ka=0,La=0,Ta=0,Qa=[];function Ua(){R++;var a=Ka,c=La,e=N;N=null;Oa(e);Ja(a,c);O()}var Sa={},Ma,Q,Ra,S=!1,Va=!1,Wa=[];
function Xa(){function a(){Va=document.pointerLockElement===b.canvas||document.mozPointerLockElement===b.canvas||document.webkitPointerLockElement===b.canvas||document.msPointerLockElement===b.canvas}b.preloadPlugins||(b.preloadPlugins=[]);if(!Ya){Ya=!0;try{T=!0}catch(e){T=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Za="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:T?null:console.log("warning: no BlobBuilder");
U="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;b.A||"undefined"!==typeof U||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),b.A=!0);b.preloadPlugins.push({canHandle:function(e){return!b.A&&/\.(jpg|jpeg|png|bmp)$/i.test(e)},handle:function(e,d,f,g){var h=null;if(T)try{h=new Blob([e],{type:$a(d)}),h.size!==e.length&&(h=new Blob([(new Uint8Array(e)).buffer],{type:$a(d)}))}catch(n){ia("Blob constructor present but fails: "+
n+"; falling back to blob builder")}h||(h=new Za,h.append((new Uint8Array(e)).buffer),h=h.getBlob());var m=U.createObjectURL(h),k=new Image;k.onload=function(){assert(k.complete,"Image "+d+" could not be decoded");var n=document.createElement("canvas");n.width=k.width;n.height=k.height;n.getContext("2d").drawImage(k,0,0);b.preloadedImages[d]=n;U.revokeObjectURL(m);f&&f(e)};k.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};k.src=m}});b.preloadPlugins.push({canHandle:function(e){return!b.K&&
e.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(e,d,f,g){function h(l){k||(k=!0,b.preloadedAudios[d]=l,f&&f(e))}function m(){k||(k=!0,b.preloadedAudios[d]=new Audio,g&&g())}var k=!1;if(T){try{var n=new Blob([e],{type:$a(d)})}catch(l){return m()}n=U.createObjectURL(n);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!k){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var l="",p=0,t=0,w=
0;w<e.length;w++)for(p=p<<8|e[w],t+=8;6<=t;){var q=p>>t-6&63;t-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[q]}2==t?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&3)<<4],l+="=="):4==t&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&15)<<2],l+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+l;h(u)}};u.src=n;ab(function(){h(u)},1E4)}else return m()}});var c=b.canvas;c&&(c.requestPointerLock=c.requestPointerLock||c.mozRequestPointerLock||
c.webkitRequestPointerLock||c.msRequestPointerLock||function(){},c.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},c.exitPointerLock=c.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),b.elementPointerLock&&
c.addEventListener("click",function(e){!Va&&b.canvas.requestPointerLock&&(b.canvas.requestPointerLock(),e.preventDefault())},!1))}}
function cb(a,c,e,d){if(c&&b.v&&a==b.canvas)return b.v;var f;if(c){var g={antialias:!1,alpha:!1,I:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof GL&&(f=GL.createContext(a,g)))var m=GL.getContext(f).F}else m=a.getContext("2d");if(!m)return null;e&&(c||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),b.v=m,c&&GL.J(f),b.M=c,Wa.forEach(function(k){k()}),Xa());return m}var db=!1,eb=void 0,V=void 0;
function fb(a,c){function e(){S=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=gb,eb&&d.requestPointerLock(),S=!0,V?("undefined"!=typeof SDL&&(J[SDL.screen>>2]=ma[SDL.screen>>2]|8388608),W(b.canvas),hb()):W(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),V?("undefined"!=typeof SDL&&(J[SDL.screen>>2]=ma[SDL.screen>>2]&-8388609),
W(b.canvas),hb()):W(d));if(b.onFullScreen)b.onFullScreen(S);if(b.onFullscreen)b.onFullscreen(S)}eb=a;V=c;"undefined"===typeof eb&&(eb=!0);"undefined"===typeof V&&(V=!1);var d=b.canvas;db||(db=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function gb(){if(!S)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var X=0;function Na(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var c=Date.now();if(0===X)X=c+1E3/60;else for(;c+2>=X;)X+=1E3/60;setTimeout(a,Math.max(X-c,0))}}function ab(a,c){noExitRuntime=!0;setTimeout(function(){G||a()},c)}
function $a(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ib=[];function hb(){var a=b.canvas;ib.forEach(function(c){c(a.width,a.height)})}
function W(a,c,e){c&&e?(a.D=c,a.B=e):(c=a.D,e=a.B);var d=c,f=e;b.forcedAspectRatio&&0<b.forcedAspectRatio&&(d/f<b.forcedAspectRatio?d=Math.round(f*b.forcedAspectRatio):f=Math.round(d/b.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}V?
(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=c&&(a.width=c),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(d!=c||f!=e?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ya,T,Za,U;function jb(a){try{a()}catch(c){C(c)}}
var Y=0,Z=null,kb=[],lb={},mb={},nb=0,ob=null,pb=[],qb=[];function rb(a){var c={},e;for(e in a)(function(d){var f=a[d];c[d]="function"===typeof f?function(){kb.push(d);try{return f.apply(null,arguments)}finally{if(G)return;var g=kb.pop(d);assert(g===d);Z&&1===Y&&0===kb.length&&(Y=0,jb(b._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.L(),ob&&(ob(),ob=null))}}:f})(e);return c}
function sb(){var a=tb(4108),c=a+12;J[a>>2]=c;J[a+4>>2]=c+4096;c=kb[0];var e=lb[c];void 0===e&&(e=nb++,lb[c]=e,mb[e]=b.asm[c]);J[a+8>>2]=e;return a}
function ub(a){if(!G)if(noExitRuntime=!0,0===Y){var c=!1,e=!1;a(function(){if(!G&&(c=!0,e)){Y=2;jb(function(){b._asyncify_start_rewind(Z)});N&&Ua();var d=(0,mb[J[Z+8>>2]])();if(!Z){var f=pb;pb=[];f.forEach(function(g){g(d)})}}});e=!0;c||(Y=1,Z=sb(),jb(function(){b._asyncify_start_unwind(Z)}),N&&(O=null,R++))}else 2===Y?(Y=0,jb(b._asyncify_stop_rewind),vb(Z),Z=null,qb.forEach(function(d){d()})):C("invalid state: "+Y)}b.requestFullscreen=function(a,c){fb(a,c)};b.requestAnimationFrame=function(a){Na(a)};
b.setCanvasSize=function(a,c,e){W(b.canvas,a,c);e||hb()};b.pauseMainLoop=function(){O=null;R++};b.resumeMainLoop=function(){Ua()};b.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};b.createContext=function(a,c,e,d){return cb(a,c,e,d)};
var wb={j:function(a,c,e){Ia.length=0;var d;for(e>>=2;d=I[c++];)Ia.push(105>d?na[++e>>1]:J[e]),++e;return Fa[a].apply(null,Ia)},f:function(a,c,e){I.copyWithin(a,c,c+e)},g:function(a){a>>>=0;var c=I.length;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var d=c*(1+.2/e);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{F.grow(Math.min(2147483648,d)-H.byteLength+65535>>>16);oa(F.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},d:function(a){ub(function(c){ab(c,
a)})},i:function(a){if(!noExitRuntime&&(G=!0,b.onExit))b.onExit(a);x(a,new fa(a))},h:function(){return 0},k:function(){},b:function(a,c,e,d){for(var f=0,g=0;g<e;g++){for(var h=J[c+8*g>>2],m=J[c+(8*g+4)>>2],k=0;k<m;k++){var n=I[h+k],u=Ha[a];if(0===n||10===n){n=1===a?ha:D;var l=u;for(var p=0,t=p+NaN,w=p;l[w]&&!(w>=t);)++w;if(16<w-p&&l.subarray&&la)l=la.decode(l.subarray(p,w));else{for(t="";p<w;){var q=l[p++];if(q&128){var xa=l[p++]&63;if(192==(q&224))t+=String.fromCharCode((q&31)<<6|xa);else{var bb=
l[p++]&63;q=224==(q&240)?(q&15)<<12|xa<<6|bb:(q&7)<<18|xa<<12|bb<<6|l[p++]&63;65536>q?t+=String.fromCharCode(q):(q-=65536,t+=String.fromCharCode(55296|q>>10,56320|q&1023))}}else t+=String.fromCharCode(q)}l=t}n(l);u.length=0}else u.push(n)}f+=m}J[d>>2]=f;return 0},c:function(a){var c=Date.now();J[a>>2]=c/1E3|0;J[a+4>>2]=c%1E3*1E3|0;return 0},e:function(a){b.setStatus("Processing: ("+a+"/100)")},memory:F,a:function(a){a=+a;return 0<=a?+ya(a+.5):+wa(a-.5)},table:ka};
(function(){function a(g){g=g.exports;g=rb(g);b.asm=g;K--;b.monitorRunDependencies&&b.monitorRunDependencies(K);0==K&&(null!==za&&(clearInterval(za),za=null),L&&(g=L,L=null,g()))}function c(g){a(g.instance)}function e(g){return Ea().then(function(h){return WebAssembly.instantiate(h,d)}).then(g,function(h){D("failed to asynchronously prepare wasm: "+h);C(h)})}var d={a:wb};K++;b.monitorRunDependencies&&b.monitorRunDependencies(K);if(b.instantiateWasm)try{var f=b.instantiateWasm(d,a);return f=rb(f)}catch(g){return D("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){if(E||"function"!==typeof WebAssembly.instantiateStreaming||Ba()||Aa("file://")||"function"!==typeof fetch)return e(c);fetch(M,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(c,function(h){D("wasm streaming compile failed: "+h);D("falling back to ArrayBuffer instantiation");return e(c)})})})();return{}})();var Ga=b.___wasm_call_ctors=function(){return(Ga=b.___wasm_call_ctors=b.asm.l).apply(null,arguments)};
b._web_main=function(){return(b._web_main=b.asm.m).apply(null,arguments)};var tb=b._malloc=function(){return(tb=b._malloc=b.asm.n).apply(null,arguments)},vb=b._free=function(){return(vb=b._free=b.asm.o).apply(null,arguments)};b.dynCall_vi=function(){return(b.dynCall_vi=b.asm.p).apply(null,arguments)};b._asyncify_start_unwind=function(){return(b._asyncify_start_unwind=b.asm.q).apply(null,arguments)};b._asyncify_stop_unwind=function(){return(b._asyncify_stop_unwind=b.asm.r).apply(null,arguments)};
b._asyncify_start_rewind=function(){return(b._asyncify_start_rewind=b.asm.s).apply(null,arguments)};b._asyncify_stop_rewind=function(){return(b._asyncify_stop_rewind=b.asm.t).apply(null,arguments)};var xb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function yb(){xb||zb();xb||(L=yb)};
function zb(){function a(){if(!xb&&(xb=!0,b.calledRun=!0,!G)){qa(sa);qa(ta);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();ua.unshift(c)}qa(ua)}}if(!(0<K)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)va();qa(ra);0<K||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=zb;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();noExitRuntime=!0;zb();
